# -*- coding: utf-8 -*-
"""Index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb

# List And It's default Functions
"""

numbers=[34,56,78,32,8]
numbers.sort() #This is the Sort Function
print(numbers)

list=['Annahari','Adnan','Majahar','shabareesh','Gnaneswar','Bharath']
list.append('Kishore') #This is append Function It's adding the new value at the end of the list
print(list)
print("The index of the value is : ",end=' ')
list.index('shabareesh')  #Printing the index of the value

letters=['a','b','c','d','e','f']
letters.insert(2,'143') #insert the value at a specific index
print(letters)

pastes=['colgate','dabur','patanjali','closeup','pepsodent']
print(pastes)
pastes.pop()#It's remove the end value in the list
print(pastes)
pastes.remove('patanjali') #It's removes the specific value in the list
print(pastes)

cities=['Hyderabad','Vizayanagaram','Vishakapatnam','Bangalore','Bombay']
print(cities)
cities.reverse() #It's reverse the values of the list
print(cities)

numbers=[1,2,3,4,5]
print(numbers)
numbers.extend([6,7,8,9,10]) #It's extend the list
print(numbers)



keys=[1523,5789,3489,1226,1523,9034,1523]
print('1523 is repeated in',keys.count(1523),end=' ')
 #It's returns the value how many times the value is repeated
print('times')

website=['google','youtube','gmail','keybr','facebook']
print(website)
website.clear() #it's clear the values in the list completely
print(website)

"""# Dictionary and It's Functions"""

dict={'Mobiles':'Oneplus, Samsung, Iphone, Realme',
      'Laptops':'Hp, Asus, Dell, Acer, Lenovo'}
print(dict)
print(dict.keys())#Print the keys
print(dict['Laptops']) #Print the value by using it's key

Student={'Name':'Annahari','Rollno':'19x51a0503','Course':'B-Tech'}
print(Student.items()) #Print the key-value pairs
Student.get('Rollno') #Get the value by using it's key
Student.pop('Course') #Remove the value by using it's key
print(Student)
Student.update({'course':'B-Tech'}) #It's update a new value in the dictionary
print(Student)
details=Student.copy() #We copy the dictionay by using copy function
print(details)

"""# Set and It's Functions"""

thisset={'Orange','Banana','Apple','Orange'}
print(type(thisset)) #Printing the type of the variable
print(thisset) #Printing the set
thisset.add('Cherry') #We add a new value in the set
print(thisset)
thisset.update(['Pineapple','Pomegranate','Papayya']) #We add a multiple values in the set
print(thisset)

set={'Pineapple', 'Banana', 'Apple', 'Papayya', 'Orange', 'Pomegranate'}
print(thisset)
print('The length of the set : ', end=' ')
print(len(thisset))#Returns the length of the set 
thisset.discard('Papayya') #It's removes the value in the list
print(thisset)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.union(n2)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.intersection(n2)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.isdisjoint(n2)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.issubset(n2)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.issuperset(n2)

n1={1,3,4,6,7}
n2={3,7,4,6,8}
n1.difference(n2)

"""# Tuple and explore default methods."""

tup=(1,2,4,5,2,8,2)
print('The number is repeated ',tup.count(2),'times')

tup=(8,5,0,0,4,5,8,7,1,0)
print('The index of the zero is : ',end=' ')
tup.index(0)

"""# Strings and explore default methods."""

Name='Anna Hariprasad'
print('The length of the name is : ', len(Name))
Surname='  anna  '
Surname.capitalize()
print(Name.upper())
print(Name.lower())
print(Surname)
print(Surname.strip())
print(Name.startswith('A'))
print(Name.endswith('d'))
print(Surname.islower())
print(Surname.isupper())
print(Surname.swapcase())
print(Name.isalnum())
print(Name.isalpha())
print(Name.isdecimal())